#%RAML 1.0 DataType
displayName: User
type: object

properties:
  _id: 
    displayName: Id
    type: string
    required: false
    description: unique Id of the User
  name:
    displayName: Name
    type: string
    required: false
    description: display name of the User
  username:
    displayName: Username
    type: string
    required: false
    description: login username of the User
  password:
    displayName: Password
    type: string
    required: false
    description: login password of the User (encrypted)

example: |
  {
    "name":"Saki",
    "username":"saki",
    "password":"XXXXXENCRYPTEDXXXXX",
    "_id":"5JEddTUBmqxIxn8G"
  }

